# SPDX-License-Identifier: MPL-2.0
# Minimal development toolchain for the Rust/SPARK CLI repository.
# Keep this project free of unrelated JavaScript/Node/Deno runtimes per the
# estate language policy.

[tools]
rust = "1.85.0"
just = "latest"
shellcheck = "latest"

[env]
RUST_BACKTRACE = "1"

[alias]
build = "cargo build --locked --workspace"
test = "cargo test --locked --workspace"
lint = "cargo clippy --locked --workspace --all-targets -- -D warnings"
fmt = "cargo fmt --all"
